package com.ambientai.data.entities

import io.objectbox.annotation.Convert
import io.objectbox.annotation.Entity
import io.objectbox.annotation.Id
import io.objectbox.converter.PropertyConverter

/**
 * Synthesized narrative understanding of user's current context.
 * Generated by the "thinker" workflow after significant state changes.
 */
@Entity
data class Narrative(
    @Id var id: Long = 0,
    var text: String,
    @Convert(converter = NarrativeTypeConverter::class, dbType = Int::class)
    var narrativeType: NarrativeType,
    var stateSnapshot: String,
    var timestamp: Long
)

enum class NarrativeType { WORKING, DAILY, WEEKLY }

class NarrativeTypeConverter : PropertyConverter<NarrativeType, Int> {
    override fun convertToDatabaseValue(entityProperty: NarrativeType?) =
        entityProperty?.ordinal ?: 0

    override fun convertToEntityProperty(databaseValue: Int?) =
        NarrativeType.entries.getOrNull(databaseValue ?: 0) ?: NarrativeType.WORKING
}