package com.ambientai.core.media

import android.util.Log
import com.ambientai.data.entities.MediaTranscript
import com.ambientai.data.entities.TranscriptSegment
import com.ambientai.data.repositories.ITranscriptSegmentRepository
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.math.sqrt

@Singleton
class SmartSegmenter @Inject constructor(
    private val segmentRepo: ITranscriptSegmentRepository,
    private val textEmbedder: TextEmbedder
) {
    companion object {
        private const val TAG = "SmartSegmenter"
        private const val SIMILARITY_THRESHOLD = 0.7f
    }
    fun segment(captions: List<Caption>, chapters: List<YouTubeChapter>, embedder: ((String) -> FloatArray)?): List<TranscriptSegment> = when {
        chapters.isNotEmpty() -> segmentByChapters(captions, chapters)
        embedder != null -> segmentByTopicShift(captions, embedder)
        else -> segmentBySentenceBoundaries(captions)
    }
    private fun segmentByChapters(captions: List<Caption>, chapters: List<YouTubeChapter>): List<TranscriptSegment> { Log.d(TAG, "Segmenting by ${chapters.size} chapters"); return chapters.map { chapter -> val chapterCaptions = captions.filter { it.startMs >= chapter.startMs && it.endMs <= chapter.endMs }; TranscriptSegment(transcriptId = 0, text = chapterCaptions.joinToString(" ") { it.text }, startMs = chapter.startMs, endMs = chapter.endMs) } }
    private fun segmentByTopicShift(captions: List<Caption>, embedder: (String) -> FloatArray): List<TranscriptSegment> { Log.d(TAG, "Segmenting by topic shift detection"); val sentences = groupIntoSentences(captions); if (sentences.size < 2) return listOf(TranscriptSegment(transcriptId = 0, text = sentences.firstOrNull()?.first ?: "", startMs = captions.firstOrNull()?.startMs ?: 0, endMs = captions.lastOrNull()?.endMs ?: 0)); val embeddings = sentences.map { (text, _) -> embedder(text) }; val segments = mutableListOf<TranscriptSegment>(); var segmentStart = 0; var segmentCaptions = mutableListOf(sentences[0]); for (i in 1 until sentences.size) { val similarity = cosineSimilarity(embeddings[i - 1], embeddings[i]); if (similarity < SIMILARITY_THRESHOLD) { val text = segmentCaptions.joinToString(" ") { it.first }; val startMs = segmentCaptions.first().second.first; val endMs = segmentCaptions.last().second.second; segments.add(TranscriptSegment(transcriptId = 0, text = text, startMs = startMs, endMs = endMs)); segmentCaptions.clear(); segmentStart = i }; segmentCaptions.add(sentences[i]) }; if (segmentCaptions.isNotEmpty()) { val text = segmentCaptions.joinToString(" ") { it.first }; val startMs = segmentCaptions.first().second.first; val endMs = segmentCaptions.last().second.second; segments.add(TranscriptSegment(transcriptId = 0, text = text, startMs = startMs, endMs = endMs)) }; Log.d(TAG, "Created ${segments.size} segments via topic shift"); return segments }
    private fun segmentBySentenceBoundaries(captions: List<Caption>, targetDurationSec: Int = 45): List<TranscriptSegment> { Log.d(TAG, "Segmenting by sentence boundaries (${targetDurationSec}s target)"); val segments = mutableListOf<TranscriptSegment>(); var currentChunk = StringBuilder(); var chunkStartMs = 0L; var chunkDurationMs = 0L; var chunkCaptions = mutableListOf<Caption>(); captions.forEach { caption -> if (chunkCaptions.isEmpty()) chunkStartMs = caption.startMs; currentChunk.append(caption.text).append(" "); chunkDurationMs += caption.durationMs; chunkCaptions.add(caption); if (chunkDurationMs >= targetDurationSec * 1000 && caption.text.matches(Regex(".*[.!?]\\s*$"))) { segments.add(TranscriptSegment(transcriptId = 0, text = currentChunk.toString().trim(), startMs = chunkStartMs, endMs = chunkCaptions.last().endMs)); currentChunk.clear(); chunkDurationMs = 0; chunkCaptions.clear() } }; if (currentChunk.isNotEmpty()) segments.add(TranscriptSegment(transcriptId = 0, text = currentChunk.toString().trim(), startMs = chunkStartMs, endMs = chunkCaptions.last().endMs)); Log.d(TAG, "Created ${segments.size} segments"); return segments }
    private fun groupIntoSentences(captions: List<Caption>): List<Pair<String, Pair<Long, Long>>> { val sentences = mutableListOf<Pair<String, Pair<Long, Long>>>(); var currentSentence = StringBuilder(); var sentenceStartMs = 0L; var sentenceCaptions = mutableListOf<Caption>(); captions.forEach { caption -> if (sentenceCaptions.isEmpty()) sentenceStartMs = caption.startMs; currentSentence.append(caption.text).append(" "); sentenceCaptions.add(caption); if (caption.text.matches(Regex(".*[.!?]\\s*$"))) { sentences.add(Pair(currentSentence.toString().trim(), Pair(sentenceStartMs, sentenceCaptions.last().endMs))); currentSentence.clear(); sentenceCaptions.clear() } }; if (currentSentence.isNotEmpty()) sentences.add(Pair(currentSentence.toString().trim(), Pair(sentenceStartMs, sentenceCaptions.last().endMs))); return sentences }
    private fun cosineSimilarity(a: FloatArray, b: FloatArray): Float { if (a.size != b.size) return 0f; var dotProduct = 0f; var normA = 0f; var normB = 0f; for (i in a.indices) { dotProduct += a[i] * b[i]; normA += a[i] * a[i]; normB += b[i] * b[i] }; return if (normA == 0f || normB == 0f) 0f else dotProduct / (sqrt(normA) * sqrt(normB)) }
    suspend fun segmentLyrics(transcriptId: Long, mediaId: Long, lyrics: String) { Log.d(TAG, "Segmenting lyrics (${lyrics.length} chars)"); if (!textEmbedder.initialize()) { Log.e(TAG, "Failed to initialize embedder - segments will not have embeddings"); return }; val cleanedLyrics = cleanGeniusMetadata(lyrics); val verses = splitIntoVerses(cleanedLyrics); if (verses.isEmpty()) { Log.w(TAG, "No verses found after cleaning"); return }; val allSegments = mutableListOf<String>(); verses.forEach { verse -> allSegments.addAll(splitVerseBySemanticSimilarity(verse)) }; val modelName = textEmbedder.getModelName(); var embeddedCount = 0; allSegments.forEachIndexed { index, segmentText -> val embedding = textEmbedder.embed(segmentText); if (embedding == null) { Log.w(TAG, "Failed to embed segment $index, skipping"); return@forEachIndexed }; TranscriptSegment(transcriptId = transcriptId, mediaId = mediaId, text = segmentText, startMs = 0, endMs = 0, embedding = embedding, embeddingModel = modelName, segmentIndex = index).also { segmentRepo.save(it); embeddedCount++ } }; Log.d(TAG, "Created ${embeddedCount}/${allSegments.size} lyrics segments with embeddings (model: $modelName, semantic line-based segmentation)") }
    private fun cleanGeniusMetadata(lyrics: String): String = lyrics.replace(Regex("^\\d+\\s+Contributors.*$", RegexOption.MULTILINE), "").replace(Regex("\\[.*?\\]"), "").trim()
    private fun splitIntoVerses(lyrics: String): List<String> = lyrics.split("\n\n").map { it.trim() }.filter { it.isNotBlank() && it.split("\\s+".toRegex()).size > 3 }
    private fun splitVerseBySemanticSimilarity(verse: String): List<String> { val lines = verse.split("\n").map { it.trim() }.filter { it.isNotBlank() }; if (lines.size <= 2) return listOf(verse); val lineEmbeddings = lines.mapNotNull { line -> textEmbedder.embed(line) }; if (lineEmbeddings.size != lines.size) return listOf(verse); val segments = mutableListOf<String>(); var currentSegment = mutableListOf(lines[0]); for (i in 1 until lines.size) { val similarity = cosineSimilarity(lineEmbeddings[i - 1], lineEmbeddings[i]); if (similarity < SIMILARITY_THRESHOLD) { segments.add(currentSegment.joinToString("\n")); currentSegment.clear() }; currentSegment.add(lines[i]) }; if (currentSegment.isNotEmpty()) segments.add(currentSegment.joinToString("\n")); return segments.filter { it.split("\\s+".toRegex()).size > 2 } }
    private fun segmentLyricsByTopicShift(verses: List<String>, embedder: (String) -> FloatArray?): List<String> { if (verses.size < 2) return verses; val embeddings = verses.mapNotNull { verse -> embedder(verse) }; if (embeddings.size != verses.size) { Log.w(TAG, "Failed to embed some verses, falling back to verse-based segmentation"); return verses }; val segments = mutableListOf<String>(); var currentSegment = mutableListOf(verses[0]); var currentEmbedding = embeddings[0]; for (i in 1 until verses.size) { val similarity = cosineSimilarity(currentEmbedding, embeddings[i]); if (similarity < SIMILARITY_THRESHOLD) { segments.add(currentSegment.joinToString("\n\n")); currentSegment.clear(); currentEmbedding = embeddings[i] }; currentSegment.add(verses[i]) }; if (currentSegment.isNotEmpty()) segments.add(currentSegment.joinToString("\n\n")); Log.d(TAG, "Topic shift: ${verses.size} verses → ${segments.size} semantic segments (threshold: $SIMILARITY_THRESHOLD)"); return segments }
}
