package com.ambientai.core.media

import android.content.Context
import android.util.Log
import com.yausername.youtubedl_android.YoutubeDL
import com.yausername.youtubedl_android.YoutubeDLRequest
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class YouTubeHandler @Inject constructor(
    @ApplicationContext private val context: Context
) {
    companion object {
        private const val TAG = "YouTubeHandler"
    }
    private val mediaDir = File(context.filesDir, "media").apply { mkdirs() }
    private val thumbnailDir = File(context.filesDir, "media/thumbnails").apply { mkdirs() }
    suspend fun initialize() = withContext(Dispatchers.IO) { runCatching { YoutubeDL.getInstance().init(context); Log.d(TAG, "YoutubeDL initialized"); try { Log.d(TAG, "Updating yt-dlp to NIGHTLY channel..."); YoutubeDL.getInstance().updateYoutubeDL(context, com.yausername.youtubedl_android.YoutubeDL.UpdateChannel.NIGHTLY); Log.d(TAG, "✅ yt-dlp updated successfully") } catch (e: Exception) { Log.w(TAG, "yt-dlp update failed (will use bundled version): ${e.message}") }; true }.getOrElse { e -> Log.e(TAG, "Failed to initialize YoutubeDL", e); false } }
    suspend fun fetchMetadata(videoUrl: String): YouTubeMetadata? = withContext(Dispatchers.IO) { runCatching { val request = YoutubeDLRequest(videoUrl).apply { addOption("--dump-json"); addOption("--skip-download"); addOption("--write-comments"); addOption("--extractor-args", "youtube:max_comments=100") }; val response = YoutubeDL.getInstance().execute(request, null); val json = JSONObject(response.out); YouTubeMetadata(id = json.optString("id", ""), title = json.optString("title", "Untitled"), channelName = json.optString("channel", "Unknown"), duration = json.optLong("duration", 0) * 1000, thumbnailUrl = json.optString("thumbnail", ""), publishDate = json.optLong("timestamp", 0) * 1000, chapters = parseChapters(json), comments = parseComments(json)) }.getOrElse { e -> Log.e(TAG, "Failed to fetch metadata for $videoUrl", e); null } }
    private fun parseChapters(json: JSONObject): List<YouTubeChapter> = runCatching { val chaptersArray = json.optJSONArray("chapters") ?: return emptyList(); (0 until chaptersArray.length()).mapNotNull { chaptersArray.optJSONObject(it)?.let { chapter -> YouTubeChapter(title = chapter.optString("title", ""), startMs = (chapter.optDouble("start_time", 0.0) * 1000).toLong(), endMs = (chapter.optDouble("end_time", 0.0) * 1000).toLong()) } } }.getOrDefault(emptyList())
    private fun parseComments(json: JSONObject): List<YouTubeComment> = runCatching { val commentsArray = json.optJSONArray("comments") ?: return emptyList(); (0 until commentsArray.length()).take(100).mapNotNull { commentsArray.optJSONObject(it)?.let { comment -> YouTubeComment(text = comment.optString("text", ""), author = comment.optString("author", "Unknown"), likeCount = comment.optInt("like_count", 0), timestamp = comment.optLong("timestamp", 0) * 1000) } } }.getOrDefault(emptyList())
    suspend fun downloadAudio(videoUrl: String, videoId: String): File? = withContext(Dispatchers.IO) { runCatching { val outputPath = File(mediaDir, "$videoId.m4a"); if (outputPath.exists()) return@withContext outputPath; Log.d(TAG, "Attempting to download audio from $videoUrl"); val playerClients = listOf("android", "tv", "ios", "mweb", "default"); val formats = listOf("bestaudio[ext=m4a]/bestaudio/best", "bestaudio", "best"); for (client in playerClients) { for (format in formats) { val extractAudio = !format.contains("[ext=m4a]"); val desc = "client=$client, format=$format" + if (extractAudio) " +extract" else ""; try { Log.d(TAG, "Trying: $desc"); val outputTemplate = if (extractAudio) outputPath.absolutePath.removeSuffix(".m4a") else outputPath.absolutePath; val request = YoutubeDLRequest(videoUrl).apply { addOption("-f", format); if (extractAudio) { addOption("-x"); addOption("--audio-format", "m4a") }; addOption("--extractor-args", "youtube:player_client=$client"); addOption("-o", outputTemplate) }; YoutubeDL.getInstance().execute(request, null); if (outputPath.exists()) { Log.d(TAG, "✅ SUCCESS: $desc - ${outputPath.absolutePath}"); return@withContext outputPath } } catch (e: Exception) { Log.w(TAG, "Failed ($desc): ${e.message?.take(100)}") } } }; Log.e(TAG, "All strategies failed for $videoUrl"); null }.getOrElse { e -> Log.e(TAG, "Download error for $videoUrl", e); null } }
    suspend fun downloadThumbnail(thumbnailUrl: String, videoId: String): File? = withContext(Dispatchers.IO) { runCatching { val outputPath = File(thumbnailDir, "$videoId.jpg"); if (outputPath.exists()) return@withContext outputPath; val connection = java.net.URL(thumbnailUrl).openConnection(); connection.connect(); connection.getInputStream().use { input -> outputPath.outputStream().use { output -> input.copyTo(output) } }; Log.d(TAG, "Downloaded thumbnail: ${outputPath.absolutePath}"); outputPath }.getOrElse { e -> Log.e(TAG, "Failed to download thumbnail from $thumbnailUrl", e); null } }
    suspend fun fetchCaptions(videoUrl: String, videoId: String, language: String = "en"): List<Caption>? = withContext(Dispatchers.IO) { runCatching { Log.d(TAG, "Attempting to fetch captions for $videoUrl"); val strategies: List<Pair<List<String>, String>> = listOf(Pair(listOf("--write-auto-sub", "--sub-lang", language), "auto-generated subs"), Pair(listOf("--write-sub", "--sub-lang", language), "manual subs"), Pair(listOf("--write-auto-sub", "--all-subs"), "all auto subs")); for ((options, desc) in strategies) { try { Log.d(TAG, "Trying caption strategy: $desc"); val tempFile = File.createTempFile("captions_$videoId", ".json3", context.cacheDir); val request = YoutubeDLRequest(videoUrl).apply { options.forEach { addOption(it) }; addOption("--skip-download"); addOption("--sub-format", "json3"); addOption("-o", tempFile.absolutePath.removeSuffix(".json3")) }; YoutubeDL.getInstance().execute(request, null); context.cacheDir.listFiles()?.filter { it.name.contains(videoId) && it.extension == "json3" }?.forEach { captionFile -> try { val captions = parseCaptionsJson(captionFile.readText()); captionFile.delete(); if (captions.isNotEmpty()) { tempFile.delete(); Log.d(TAG, "✅ SUCCESS with caption strategy: $desc - ${captions.size} captions"); return@withContext captions } } catch (e: Exception) { Log.w(TAG, "Failed to parse caption file ${captionFile.name}: ${e.message}") } }; tempFile.delete(); Log.d(TAG, "Caption strategy '$desc' found no captions") } catch (e: Exception) { Log.w(TAG, "Caption strategy '$desc' failed: ${e.message}") } }; Log.d(TAG, "All caption strategies returned empty results"); emptyList<Caption>() }.getOrElse { e -> Log.e(TAG, "Failed to fetch captions for $videoUrl", e); null } }
    private fun parseCaptionsJson(jsonText: String): List<Caption> = runCatching { val json = JSONObject(jsonText); val events = json.optJSONArray("events") ?: return emptyList(); (0 until events.length()).mapNotNull { events.optJSONObject(it)?.let { event -> val segs = event.optJSONArray("segs") ?: return@mapNotNull null; val text = (0 until segs.length()).mapNotNull { segs.optJSONObject(it)?.optString("utf8") }.joinToString(""); if (text.isBlank()) null else Caption(text = text.trim(), startMs = (event.optDouble("tStartMs", 0.0)).toLong(), durationMs = (event.optDouble("dDurationMs", 0.0)).toLong()) } } }.getOrDefault(emptyList())
    fun deleteMedia(videoId: String) { File(mediaDir, "$videoId.m4a").delete(); File(thumbnailDir, "$videoId.jpg").delete() }
}
